# Audiobookshelf to Hardcover Sync Tool
# Sync your audiobook listening progress from Audiobookshelf to Hardcover
#
# Quick Start:
# 1. Copy config/config.yaml.example to config/config.yaml
# 2. Edit config/config.yaml with your settings
# 3. Run: docker-compose up -d
#
# For local development/testing, use:
#   docker-compose -f docker-compose.local.yml up -d
#
# This compose file uses the published GHCR image.
# For local builds, use docker-compose.local.yml instead.

services:
  abs-hardcover-sync:
    # build: .  # Uncomment for local development
    image: ghcr.io/rohit-purandare/audiobookshelf-hardcover-sync:latest
    container_name: abs-hardcover-sync
    restart: unless-stopped
    user: "1000:1000"  # Run as current user to avoid permission issues
    environment:
      - PYTHONPATH=/app
      - TZ=Etc/UTC  # Set to UTC by default; change to your local timezone if needed
    volumes:
      # Mount config files for persistence
      - ./config/config.yaml:/app/config/config.yaml:ro  # Mount your config file
      # Mount cache directory for persistence
      - ./data:/app/data
      # Removed old cache file mounts
    # Interactive mode for CLI
    stdin_open: true
    tty: true
    # Use host network for potential local API access
    network_mode: host
    # Default command - can be overridden
    command: ["cron"]
    # Healthcheck for Compose-level monitoring
    healthcheck:
      test: ["CMD", "python", "src/main.py", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 