services:
  abs-hardcover-sync:
    # Pulls from GitHub Container Registry: https://github.com/rohit-purandare/audiobookshelf-hardcover-sync/pkgs/container/audiobookshelf-hardcover-sync
    image: ghcr.io/rohit-purandare/audiobookshelf-hardcover-sync:latest
    # Uncomment to build locally instead of pulling
    # build: .
    container_name: abs-hardcover-sync
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
    volumes:
      # Mount config files for persistence
      - ./config/secrets.env:/app/config/secrets.env:ro
      - ./.progress_cache.json:/app/.progress_cache.json
      - ./.edition_cache.json:/app/.edition_cache.json
    # Interactive mode for CLI
    stdin_open: true
    tty: true
    # Use host network for potential local API access
    network_mode: host
    # Default command - can be overridden
    command: ["cron"]
    # Healthcheck for Compose-level monitoring
    healthcheck:
      test: ["CMD", "python", "src/main.py", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 